name: Java CI
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Cache
              uses: actions/cache@v4
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                    ${{ runner.os }}-maven-
            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                distribution: corretto
                java-version: 22
            - name: Build with Maven
              run: ./mvnw --batch-mode --no-transfer-progress verify --file pom.xml

            - name: Upload Jar
              uses: actions/upload-artifact@v4
              with:
                name: Upload results
                path: |
                    target/jmh-results.json
